config/routes.rb
Rails.application.routes.draw do

  root to: "posts#index"

  delete "comentarios/:post_id/:comentario_id", to: "comentarios#destroy", as: :post_comentario

  get "comentarios/:post_id/:comentario_id", to: "comentarios#edit", as: :edit_comentario

  patch "comentarios/:post_id/:comentario_id", to: "comentarios#update", as: :update_comentario

  resources :posts do
    post "comentarios", to: "comentarios#create"
  end

end

app/models/comentario.rb
class Comentario
  include Mongoid::Document
  include Mongoid::Timestamps

  embedded_in :post, inverse_of: :comentarios

  validates_presence_of :nome_usuario, :texto

  field :nome_usuario, type: String
  field :texto, type: String
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  
  embeds_many :comentarios

  validates_presence_of :titulo, :conteudo
  validates_length_of :conteudo, minimum: 15

  field :titulo, type: String
  field :conteudo, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def formata_data(data)
  	data.strftime("%d/%m/%Y ás %H:%M ")
  end

  helper_method :formata_data
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController

	def create
		@post = recupera_post
    	@comentario = @post.comentarios.build(comentario_params)
	    if @comentario.save
	    	flash[:notice] = "Comentário foi criado com sucesso!"
	    end

	    redirect_to @post
	end

	def destroy
		@post = recupera_post
		@comentario = recupera_comentario
		@comentario.destroy

		redirect_to @comentario.post, notice: "Comentário apagado com sucesso."
	end

	def edit
		@post = recupera_post
		@comentario = recupera_comentario
	end

	def update
		@post = recupera_post
		@comentario = recupera_comentario.update(comentario_params)
		
		redirect_to @post
	end

	private 

    def comentario_params
        params.require(:comentario).permit(:nome_usuario, :texto)
    end 

    def recupera_post
    	@post = Post.find(params[:post_id])
    end

    def recupera_comentario
    	recupera_post.comentarios.find(params[:comentario_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").paginate :page => params[:page], :per_page => 10
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post criado com sucesso.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :conteudo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comentarios/_comentario.html.erb
<h4><%= comentario.nome_usuario %> said:</h4>
<%= simple_format comentario.texto %>
Enviado em: <%= formata_data(comentario.created_at)%> 
<br>
Atualizado em: <%= formata_data(comentario.updated_at)%>
<br>
<%= link_to "Deletar", [@post, comentario], :method => :delete, :data => {:confirm => 'Você tem certeza?'} %> |
<%= link_to 'Editar',  edit_comentario_path(@post, comentario) %>

<br>

app/views/comentarios/_form.html.erb
<%= form_for [@post, Comentario.new] do |f| %>
  <div>
    <%= f.label :Nome %><br />
    <%= f.text_field :nome_usuario %>
  </div>
  <br>
  <div>
    <%= f.label :Comentário %><br />
    <%= f.text_area :texto %>
  </div>
  <div>
    <%= f.submit "Enviar", :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>editar</h1>
<%= form_for [@post, @comentario] do |f| %>
  <div>
    <%= f.label :nome_usuario %><br />
    <%= f.text_field :nome_usuario %>
  </div>
  <div>
    <%= f.label :texto %><br />
    <%= f.text_area :texto %>
  </div>
  <div>
   <div class="actions">
    <%= f.submit "Atualizar", :class => "btn btn-primary"  %>
  </div>
  <br>
  <br>
  <br>
  <div class ="btn btn-default" >
    <%= link_to 'Voltar', :controller => "posts", :action => "index"%>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog do Matheus</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <nav class="navbar-inner">
          <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="brand">BLOG DO MATHEUS</div>
                  <ul class="nav nav-pills">
                    <li class="active"><a href="/">Home</a></li>
                    <li class="active"><a href="/posts/new">Novo Post</a></li>
                  </ul>
            </div>
          </div>
        </div>
      </nav>
    <div id="main" role="main">
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> Esse post não pode ser salvo:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>

  </div>
  <div class="field">
    <%= f.label :conteudo %><br>
    <%= f.text_area :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editando Post</h1>

<%= render 'form' %>

<br>
<div class ="btn btn-default" >
	<%= link_to 'Voltar', :controller => "posts", :action => "index"%>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="well">
    <article class="post-blog">
      <p><h2><%= post.titulo %></h2></p>
      <p>Criado em:<%= formata_data(post.created_at)%></p>
      <p>Atualizado em:<%= formata_data(post.updated_at)%></p>
      <p class="texto-post conteudo-post"><%=post.conteudo.truncate(50, omission: '... (continua)') %></p>
      <div class ="btn btn-info" >
        <%= link_to 'Ver', :controller => "posts", :action => "show", :id => post %>
      </div>
      <div class ="btn btn-info" >
        <%= link_to 'Editar', :controller => "posts", :action => "edit", :id => post %>
      </div>
      <div class ="btn btn-danger" >
        <%= link_to 'Deletar', post_path(post), :method => :delete, :data => {:confirm => 'Você tem certeza?'}  %> 
      </div>
    </article>
  </div>
<% end %>
<br>

<%= will_paginate @posts, :class => "pager" %>
  

app/views/posts/new.html.erb
<h1>Novo Post</h1>

<%= render 'form' %>


<div class ="btn btn-default" >
	<%= link_to 'Voltar', :controller => "posts", :action => "index"%>
</div>

app/views/posts/show.html.erb
<div class="well">
      <p><h2><%= @post.titulo %></h2></p>
      <p>Criado em:<%= formata_data(@post.created_at)%></p>
      <p>Atualizado em:<%= formata_data(@post.updated_at)%></p>
	  <p class="conteudo-post"><%= @post.conteudo %></p>  
</div>

<h2>Novo comentário</h2>
<%= render "comentarios/form" %>
<h2>Comentários</h2>

<%= pluralize(@post.comentarios.size, "comentário") %> 
<%= render @post.comentarios.paginate :page => params[:page], :per_page => 10  %>
<br>
<br>
<br>
<div class="pager">
	<%= will_paginate @post.comentarios.paginate :page => params[:page], :per_page => 10 %> 
</div>
<div <div class="btn btn-default">
	<%= link_to 'Voltar', :controller => "posts", :action => "index" %>
</div>